version: '2.4'

networks:
    pk_nginx-php74-mysql8:

services:
    # nginx
    nginx-pk:
        image: nginx:stable-alpine
        container_name: nginx-pk
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/http.d/default.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

        depends_on:
            - php74-pk
        networks:
            - pk_nginx-php74-mysql8
    # php
    php74-pk:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-pk
        ports:
            - 9000
        volumes:
            - ./app:/var/www/project
        networks:
            - pk_nginx-php74-mysql8
    #mailhog
    mailhog:
        container_name: mailhog-pk
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - pk_nginx-php74-mysql8
    # mysql
    mysql8-pk:
        platform: linux/x86_64
        image: mysql:8
        container_name: mysql8-pk
        ports:
            - "3306:3306"
        volumes:
            - mysqldata-pk:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_DATABASE=kakarot
            - MYSQL_USER=kakarot
            - MYSQL_PASSWORD=symfonyDev1234
            - MYSQL_ROOT_PASSWORD=sd9gsFnsn304s
        networks:
            - pk_nginx-php74-mysql8
volumes:
    mysqldata-pk:
        driver: local
